version: "3"

services:
  webapp:
    container_name: onboarding_app
    tty: true
    restart: always
    build: .
    ports:
      - 4200:4200
    working_dir: "/usr/src/app"
    volumes:
      - .:/usr/src/app
